import { Faturamento, Fornecedor, Certidao } from "@/types";

export const mockFornecedores: Fornecedor[] = [
  {
    id: "f1",
    razao_social: "TV ASA BRANCA LTDA",
    cnpj: "02.370.536/0001-24",
    tipo: "midia",
    contato_nome: "Carlos Menezes",
    contato_whatsapp: "82999990001",
    contato_email: "financeiro@tvasabranca.com.br",
    telefone: "8233330001",
    ativo: true,
  },
  {
    id: "f2",
    razao_social: "MACEIÓ FM RÁDIOS DIFUSORAS LTDA",
    cnpj: "57.888.376/0001-54",
    tipo: "midia",
    contato_nome: "Ana Lima",
    contato_whatsapp: "82999990002",
    contato_email: "nf@maceio.fm",
    ativo: true,
  },
  {
    id: "f3",
    razao_social: "CLIC PRODUÇÕES E EDUCAÇÃO LTDA",
    cnpj: "18.529.606/0001-84",
    tipo: "producao",
    contato_nome: "Pedro Santos",
    contato_whatsapp: "82999990003",
    contato_email: "pedro@clicproducoes.com.br",
    ativo: true,
  },
  {
    id: "f4",
    razao_social: "CS7 SERVIÇOS LTDA",
    cnpj: "22.449.622/0001-34",
    tipo: "producao",
    contato_nome: "Marcos Ferreira",
    contato_whatsapp: "82999990004",
    contato_email: "nf@cs7servicos.com.br",
    ativo: true,
  },
];

export const mockCertidoes: Certidao[] = [
  {
    id: "c1",
    tipo: "federal",
    label: "Federal (Receita Federal + PGFN)",
    validade: "2026-07-29",
    status: "valida",
  },
  {
    id: "c2",
    tipo: "estadual",
    label: "Estadual (SEFAZ-AL)",
    validade: "2026-05-05",
    status: "valida",
  },
  {
    id: "c3",
    tipo: "municipal",
    label: "Municipal (SEMFAZ Maceió)",
    validade: "2026-06-29",
    status: "valida",
  },
  {
    id: "c4",
    tipo: "fgts",
    label: "FGTS (Caixa Econômica Federal)",
    validade: "2026-04-26",
    status: "vencida",
  },
  {
    id: "c5",
    tipo: "trabalhista",
    label: "Trabalhista (TST)",
    validade: "2026-04-13",
    status: "vencida",
  },
  {
    id: "c6",
    tipo: "falencia",
    label: "Falência/Concordata (TJAL)",
    validade: "2026-05-06",
    status: "vencendo",
  },
];

export const mockFaturamentos: Faturamento[] = [
  {
    id: "fat-001",
    iclips_job_id: "#4350",
    iclips_proposta_id: "5037",
    nome_campanha: "TRANSFERÊNCIA DIGITAL",
    cliente_nome: "DETRAN ALAGOAS",
    cliente_tipo: "governo_al",
    secretaria: "Departamento Estadual de Trânsito",
    empenho: "2026NE00913",
    status: "docs_fornecedores",
    etapa_atual: 2,
    etapas: [
      { numero: 1, nome: "Iniciar Faturamento", status: "concluida", iniciada_em: "2026-05-10", concluida_em: "2026-05-10", retornos: 0 },
      { numero: 2, nome: "Documentação Fornecedores", status: "em_andamento", iniciada_em: "2026-05-11", retornos: 0 },
      { numero: 3, nome: "Revisão de Documentação", status: "pendente", retornos: 0 },
      { numero: 4, nome: "Documentação Agência", status: "pendente", retornos: 0 },
      { numero: 5, nome: "Revisão do Processo", status: "pendente", retornos: 0 },
      { numero: 6, nome: "Publicação", status: "pendente", retornos: 0 },
      { numero: 7, nome: "Aguardando Validação", status: "pendente", retornos: 0 },
      { numero: 8, nome: "Conclusão", status: "pendente", retornos: 0 },
    ],
    custos_internos: [
      { codigo: "Item 05", servico: "Criação de layout para jornal 1 página", qtde: 2, valor_unitario: 3262.48, valor_total: 6524.96 },
      { codigo: "Item 08", servico: "Adaptação de layout para revista 1 página", qtde: 2, valor_unitario: 1251.32, valor_total: 2502.64 },
      { codigo: "Item 61", servico: "Adaptação de roteiro para VT 30\"", qtde: 1, valor_unitario: 1638.14, valor_total: 1638.14 },
      { codigo: "Item 63", servico: "Criação de layout para cartelas eletrônicas", qtde: 4, valor_unitario: 567.78, valor_total: 2271.12 },
      { codigo: "Item 67", servico: "Criação de layout para outdoor", qtde: 2, valor_unitario: 2553.39, valor_total: 5106.78 },
      { codigo: "Item 62", servico: "Criação de roteiros para VT de 60\"", qtde: 4, valor_unitario: 4232.635, valor_total: 16930.54 },
    ],
    fornecedores: [
      {
        id: "fp1",
        fornecedor: mockFornecedores[0],
        valor: 255.00,
        honorarios: 20.40,
        valor_total: 275.40,
        nf_numero: undefined,
        link_token: "tok_abc123",
        prazo_dias: 5,
        dias_cobrados: 2,
        status: "parcial",
        documentos: [
          { tipo: "nf", label: "Nota Fiscal", status: "pendente" },
          { tipo: "pi", label: "PI – Pedido de Inserção", status: "enviado", arquivo_url: "#" },
          { tipo: "comprovacao", label: "Comprovação de Veiculação", status: "pendente" },
          { tipo: "tabela_orcamento", label: "Tabela de Preços / Orçamento", status: "pendente" },
        ],
      },
      {
        id: "fp2",
        fornecedor: mockFornecedores[1],
        valor: 5712.80,
        honorarios: 456.00,
        valor_total: 6168.80,
        link_token: "tok_def456",
        prazo_dias: 5,
        dias_cobrados: 0,
        status: "aguardando",
        documentos: [
          { tipo: "nf", label: "Nota Fiscal", status: "pendente" },
          { tipo: "pi", label: "PI – Pedido de Inserção", status: "pendente" },
          { tipo: "comprovacao", label: "Comprovação de Veiculação", status: "pendente" },
          { tipo: "tabela_orcamento", label: "Tabela de Preços", status: "pendente" },
        ],
      },
      {
        id: "fp3",
        fornecedor: mockFornecedores[2],
        valor: 150000.00,
        honorarios: 12000.00,
        valor_total: 162000.00,
        link_token: "tok_ghi789",
        prazo_dias: 5,
        dias_cobrados: 2,
        status: "aguardando",
        documentos: [
          { tipo: "nf", label: "Nota Fiscal", status: "pendente" },
          { tipo: "evidencia", label: "Evidência de Produção", status: "pendente" },
          { tipo: "orcamento_1", label: "Orçamento 1", status: "pendente" },
          { tipo: "orcamento_2", label: "Orçamento 2", status: "pendente" },
          { tipo: "orcamento_3", label: "Orçamento 3", status: "pendente" },
        ],
      },
    ],
    valor_total: 567109.20,
    criado_em: "2026-05-10",
    atualizado_em: "2026-05-25",
    responsavel_midia: "VS",
    responsavel_faturamento: "WK",
  },
  {
    id: "fat-002",
    iclips_job_id: "#4822",
    iclips_proposta_id: "5102",
    nome_campanha: "LANÇAMENTO PROJETO ROTA DOS CORAIS",
    cliente_nome: "SEBRAE ALAGOAS",
    cliente_tipo: "sebrae",
    status: "aguardando_inicio",
    etapa_atual: 1,
    etapas: [
      { numero: 1, nome: "Iniciar Faturamento", status: "pendente", retornos: 0 },
      { numero: 2, nome: "Documentação Fornecedores", status: "pendente", retornos: 0 },
      { numero: 3, nome: "Revisão de Documentação", status: "pendente", retornos: 0 },
      { numero: 4, nome: "Documentação Agência", status: "pendente", retornos: 0 },
      { numero: 5, nome: "Revisão do Processo", status: "pendente", retornos: 0 },
      { numero: 6, nome: "Publicação", status: "pendente", retornos: 0 },
      { numero: 7, nome: "Aguardando Validação", status: "pendente", retornos: 0 },
      { numero: 8, nome: "Conclusão", status: "pendente", retornos: 0 },
    ],
    custos_internos: [],
    fornecedores: [],
    valor_total: 84500.00,
    criado_em: "2026-05-24",
    atualizado_em: "2026-05-24",
    responsavel_midia: "VS",
  },
  {
    id: "fat-003",
    iclips_job_id: "#4818",
    iclips_proposta_id: "5089",
    nome_campanha: "COPA SUSTENTÁVEL BRK RMM",
    cliente_nome: "BRK",
    cliente_tipo: "brk",
    status: "revisao_processo",
    etapa_atual: 5,
    etapas: [
      { numero: 1, nome: "Iniciar Faturamento", status: "concluida", retornos: 0 },
      { numero: 2, nome: "Documentação Fornecedores", status: "concluida", retornos: 0 },
      { numero: 3, nome: "Revisão de Documentação", status: "concluida", retornos: 1, inconformidade_motivo: "NF do fornecedor CS7 com valor incorreto — corrigida" },
      { numero: 4, nome: "Documentação Agência", status: "concluida", retornos: 0 },
      { numero: 5, nome: "Revisão do Processo", status: "em_andamento", retornos: 0 },
      { numero: 6, nome: "Publicação", status: "pendente", retornos: 0 },
      { numero: 7, nome: "Aguardando Validação", status: "pendente", retornos: 0 },
      { numero: 8, nome: "Conclusão", status: "pendente", retornos: 0 },
    ],
    custos_internos: [],
    fornecedores: [],
    valor_total: 32000.00,
    criado_em: "2026-05-02",
    atualizado_em: "2026-05-23",
  },
];
